export const PUBLICATION = [
  {
    code: "O1",
    title: "SessionRerank+",
    venueFit: "ACL / EMNLP Findings, or IR workshops (SIGIR short) if ToolBench numbers hold",
    ready: false,
    claim: "Session-conditioned API reranking with a co-activation cache is a distinct retrieval chapter versus turn-amnesic ToolLLM/ToolRerank. Empirical bake-off is future work, not a proposal result.",
    evidence: [
      "Real algorithm in src/sessionrerank/model/{session_rerank,coactivation,pheromone}.py.",
      "Agri demo on 15 Karnataka APIs and an HF Space.",
      "Kaggle notebook exists.",
    ],
    blockers: [
      "Reported agri NDCG is on a small Karnataka set, not the full ToolBench 16k index.",
      "No unit tests in the GitHub repo.",
      "agri_extension/__init__.py imported a missing BioRerankAgri module (now pointed at SessionRerankPlus).",
      "Web demo used keyword base scores, not Gemma embeddings.",
    ],
    next: "Run ToolEval on G1–G3 with frozen weights, ablate w_cooc, report CI over seeds.",
  },
  {
    code: "O2",
    title: "APRR",
    venueFit: "AAMAS / ICLR workshop / systems+NLP hybrid; ACL only with ToolBench Pareto vs MasRouter",
    ready: false,
    claim: "A training-free affinity router over tool-specialist agents is a distinct routing chapter versus MasRouter/RouteLLM/PILOT. Cost or win-rate is not claimed here.",
    evidence: [
      "Core router implements P∝W^α η^β ψ^γ and the 1/L² latency deposit.",
      "tables/table1_main_results.csv and a Vercel results dashboard exist.",
      "tests/test_router.py covers the core router.",
    ],
    blockers: [
      "Docstring Eq. 3 (κ·success/cost) does not match the code (κ·reward·1/L²·1/lat_norm).",
      "HF 'APRR-core' is CTGR with threshold 1.1, not APRRRouter.route.",
      "Simulator fidelity is a review concern in the bundled MIT/Harvard notes.",
      "CTGR/FTDR lack tests.",
    ],
    next: "Align paper Eq. 3 with code, add CTGR/FTDR tests, compare against MasRouter on the same ToolBench split.",
  },
  {
    code: "O3",
    title: "MNCD",
    venueFit: "IEEE Access / Future Internet / workshop on multi-agent systems; not NeurIPS oral as-is",
    ready: false,
    claim: "Gossip mesh + score-sum consensus over tool IDs is a distinct coordination chapter versus AutoGen/MetaGPT chat. Survival-rate numbers from synthetic harnesses are not proposal commitments.",
    evidence: [
      "Stdlib mesh with pub/sub, gossip, R=3 LWW KV, distress channel.",
      "Eval harness S1–S6 and committed metrics.",
      "README now distinguishes score-sum from Borda.",
    ],
    blockers: [
      "Default consensus is score-sum; calling it Borda in intros is a review-killing error.",
      "Karnataka fixture invents tool names, not prices — but is still synthetic.",
      "No tests/ directory; committed metrics are MockLLM only.",
      "Peer-weight equation in README ≠ EMA success/latency in code.",
    ],
    next: "Wire live AGMARKNET into eval, report Borda vs score-sum ablation, add unit tests for gossip/replicate.",
  },
  {
    code: "O4",
    title: "FCNP",
    venueFit: "ACL Findings (context compression) or Scientific Reports-style systems paper if stats stabilize",
    ready: false,
    claim: "Kirchhoff/Physarum pruning with citation write-back is a distinct memory chapter versus LLMLingua. Compression ratios are not proposal commitments.",
    evidence: [
      "Full pytest suite including live-selection logic (Karnataka-first, then other live states).",
      "Pruner is the Tero-style conductance loop, not LFU.",
      "Honest coverage-gap notes for Karnataka-absent days.",
    ],
    blockers: [
      "Synthetic F1 is unseeded and swings 0.11–0.72.",
      "BM25/LLMLingua hitting F1=1.0 on the synthetic fixture is a keyword leak.",
      "HF Space still falls back to a bundled snapshot on live errors (demo convenience, not the lab policy).",
    ],
    next: "Seed the harness, remove keyword leakage, Wilcoxon across ≥10 seeds, compare on LongBench or real mandi pages.",
  },
  {
    code: "INT",
    title: "Integrated ACRS pipeline",
    venueFit: "Demo track (EMNLP/ACL) or a domain journal (Computers and Electronics in Agriculture) once live",
    ready: false,
    claim: "Four named artefacts compose into one live farmer loop on data.gov.in.",
    evidence: [
      "This deployment HTTP-calls /api/services/{satr,aprr,mncd,fcnp} in order.",
      "Mandi execution is live-only; missing keys fail loudly.",
      "Two-turn session memory is tested.",
    ],
    blockers: [
      "phd-agentic-ai-master on GitHub is still mostly proposal PPTX, not the runtime.",
      "No full ToolBench 16k index in this lab (schema-compatible catalog + Karnataka APIs).",
      "Google Slides source remains private (401).",
    ],
    next: "Keep claims at proposal/demo strength until ToolBench+ToolEval and multi-seed FCNP are in the master repo.",
  },
] as const;
